# Generated by Django 2.1.1 on 2018-12-17 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20181206_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_category', to='products.Category'),
        ),
    ]
