# Generated by Django 2.1.3 on 2019-01-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='sold_bill',
            field=models.IntegerField(default=True),
        ),
    ]
