# Generated by Django 2.1.3 on 2019-02-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_variation_sold_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeatured',
            name='upload_to_jumbotron',
            field=models.BooleanField(default=False),
        ),
    ]
