# Generated by Django 2.1.3 on 2019-02-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productfeatured_upload_to_jumbotron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='sold_bill',
            field=models.IntegerField(default=0),
        ),
    ]
