# Generated by Django 2.1.3 on 2019-02-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20190202_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variation',
            name='inventory',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
