# Generated by Django 2.1.3 on 2019-02-05 09:08

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20190205_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default=1, upload_to=products.models.image_upload_to_brand),
            preserve_default=False,
        ),
    ]
