# Generated by Django 2.1.3 on 2019-02-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.ManyToManyField(blank=True, null=True, to='products.Brand'),
        ),
    ]
