# Generated by Django 2.1.3 on 2019-02-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utily', '0002_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ratings',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
